server:
  port: 8086
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
hm:
  swagger:
    title: 支付服务接口文档
    package: com.hmall.pay.controller
  db:
    database: hm-pay
spring:
  rabbitmq:
    host: 192.168.126.131 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码

